### ISSUE TITLE
建议：开启当前 org 的 discussion 功能，方便大家讨论

### ISSUE THREAD

**Issue by LinuxSuRen** [summer-ospp/help#215]
效果如下

![image](https://github.com/summer-ospp/help/assets/1450685/2dfae06a-ba4c-4803-99e4-05d9c2c6cbc7)

开启的参考步骤如下

![image](https://github.com/summer-ospp/help/assets/1450685/49940813-562d-456b-90d7-50964e21f56b)

**Comment by yinjiayi** [comment]
已经打开。https://github.com/orgs/summer-ospp/discussions
