### ISSUE TITLE
社区注册和项目提交是明天开始吗 | Could you please confirm if the community registration and project submission will commence tomorrow?

### ISSUE THREAD

**Issue by cubxxw** [summer-ospp/help#225]
I would like to inquire about the process of registering for the OSPP program in our community. Is there a need to subscribe to the calendar schedule, and are there any specific requirements? Thank you.

**Comment by HungryFish034** [comment]
Hi, the community registration is not open yet. OSPP 2024 will start next Monday and detailed timeline will be shown on the official website then.

**Comment by cubxxw** [comment]
> Hi, the community registration is not open yet. OSPP 2024 will start next Monday and detailed timeline will be shown on the official website then.您好，社区注册尚未开放。OSPP 2024将于下周一开始，届时官方网站将显示详细的时间轴。

thx

**Comment by cubxxw** [comment]
> Hi, the community registration is not open yet. OSPP 2024 will start next Monday and detailed timeline will be shown on the official website then.

thx
